# Generated by Django 5.2.5 on 2025-09-21 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=3)),
                ('estado_nuevo', models.CharField(max_length=3)),
                ('comentario', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='activos.registromantenimiento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ot'], name='core_histor_ot_id_ff1e54_idx'), models.Index(fields=['estado_nuevo'], name='core_histor_estado__79557b_idx'), models.Index(fields=['-timestamp'], name='core_histor_timesta_f30df4_idx')],
            },
        ),
    ]
