# Generated by Django 5.2.5 on 2025-08-27 17:16

import django.db.models.deletion
import horometro.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField()),
                ('semana', models.PositiveSmallIntegerField()),
                ('valor_ciclos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('umbral', models.DecimalField(decimal_places=2, default=70000, max_digits=12)),
                ('estado', models.CharField(choices=[('NUEVA', 'Nueva'), ('EN_PROCESO', 'En proceso'), ('CERRADA', 'Cerrada')], default='NUEVA', max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas_mant', to='activos.activo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('activo', 'anio', 'semana'), name='uniq_alerta_activo_anio_semana')],
            },
        ),
        migrations.CreateModel(
            name='LecturaHorometro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField()),
                ('semana', models.PositiveSmallIntegerField()),
                ('lectura', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ciclos_oracle', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ciclo_ultimo_preventivo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ciclos_desde_ultimo_preventivo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fuente_archivo', models.FileField(blank=True, null=True, upload_to=horometro.models.path_horometro_imports)),
                ('fila_excel', models.PositiveIntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturas_horometro', to='activos.activo')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-anio', '-semana', 'activo__codigo'),
                'indexes': [models.Index(fields=['anio', 'semana'], name='horometro_l_anio_b4a393_idx'), models.Index(fields=['activo'], name='horometro_l_activo__b86b3e_idx')],
                'constraints': [models.UniqueConstraint(fields=('activo', 'anio', 'semana'), name='uniq_lectura_activo_anio_semana')],
            },
        ),
    ]
