# Generated by Django 5.2.5 on 2025-08-14 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturaHorometro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField()),
                ('semana', models.PositiveSmallIntegerField()),
                ('lectura', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fuente_archivo', models.FileField(blank=True, null=True, upload_to='horometro/')),
                ('fila_excel', models.PositiveIntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturas_horometro', to='activos.activo')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['anio', 'semana'], name='horometro_l_anio_b4a393_idx'), models.Index(fields=['activo'], name='horometro_l_activo__b86b3e_idx')],
                'unique_together': {('activo', 'anio', 'semana')},
            },
        ),
    ]
