# Generated by Django 5.2.5 on 2025-09-02 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0006_alter_novedad_etapa_and_more'),
        ('horometro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertamantenimiento',
            options={'ordering': ['-anio', '-semana', 'activo__codigo']},
        ),
        migrations.AddField(
            model_name='alertamantenimiento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertamantenimiento',
            name='lectura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='horometro.lecturahorometro'),
        ),
        migrations.AddField(
            model_name='alertamantenimiento',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alertamantenimiento',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas_mantenimiento', to='activos.activo'),
        ),
        migrations.AddIndex(
            model_name='alertamantenimiento',
            index=models.Index(fields=['estado'], name='horometro_a_estado_a66636_idx'),
        ),
        migrations.AddIndex(
            model_name='alertamantenimiento',
            index=models.Index(fields=['anio', 'semana'], name='horometro_a_anio_29cd35_idx'),
        ),
        migrations.AddIndex(
            model_name='alertamantenimiento',
            index=models.Index(fields=['activo'], name='horometro_a_activo__608ad4_idx'),
        ),
    ]
