# Generated by Django 5.2.5 on 2025-08-14 20:51

import horometro.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
        ('horometro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lecturahorometro',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='lecturahorometro',
            name='fuente_archivo',
            field=models.FileField(blank=True, null=True, upload_to=horometro.models.path_horometro_imports),
        ),
        migrations.AddConstraint(
            model_name='lecturahorometro',
            constraint=models.UniqueConstraint(fields=('activo', 'anio', 'semana'), name='uniq_lectura_activo_anio_semana'),
        ),
    ]
