# Generated by Django 5.2.5 on 2025-08-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horometro', '0002_alter_lecturahorometro_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturahorometro',
            name='ciclos_desde_ultimo_preventivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lecturahorometro',
            name='ciclos_oracle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lecturahorometro',
            name='fecha_ultimo_preventivo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
