# Generated by Django 5.2.5 on 2025-08-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horometro', '0003_lecturahorometro_ciclos_desde_ultimo_preventivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturahorometro',
            name='fecha_ultimo_preventivo',
        ),
        migrations.AddField(
            model_name='lecturahorometro',
            name='ciclo_ultimo_preventivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
