# Generated by Django 5.2.5 on 2025-08-16 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
        ('horometro', '0004_remove_lecturahorometro_fecha_ultimo_preventivo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturahorometro',
            options={'ordering': ('-anio', '-semana', 'activo__codigo')},
        ),
        migrations.CreateModel(
            name='AlertaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField()),
                ('semana', models.PositiveSmallIntegerField()),
                ('valor_ciclos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('umbral', models.DecimalField(decimal_places=2, default=70000, max_digits=12)),
                ('estado', models.CharField(choices=[('NUEVA', 'Nueva'), ('EN_PROCESO', 'En proceso'), ('CERRADA', 'Cerrada')], default='NUEVA', max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas_mant', to='activos.activo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('activo', 'anio', 'semana'), name='uniq_alerta_activo_anio_semana')],
            },
        ),
    ]
