# Generated by Django 5.2.5 on 2025-09-22 00:47

import activos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('obligatorio', models.BooleanField(default=False)),
                ('requiere_evidencia', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EstadoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamiliaActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemMantenible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=100)),
                ('nombre', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ('nombre', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TareaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Tarea')),
                ('descripcion', models.TextField(blank=True, help_text='Instrucciones detalladas de la tarea.')),
            ],
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('numero_activo', models.CharField(max_length=255, verbose_name='# Activo')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes')),
                ('componentes', models.ManyToManyField(blank=True, limit_choices_to={'ubicacion__tipo__in': ['SUBUNIDAD', 'ITEM', 'PARTE']}, related_name='es_parte_de', to='activos.activo', verbose_name='Componentes')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='activos.categoriaactivo')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='activos.estadoactivo')),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='activos.familiaactivo')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('archivo', models.FileField(upload_to='activos/docs/%Y/%m/%d/')),
                ('subido', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='activos.activo')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenciaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='evidencias_mantenimiento/%Y/%m/%d/')),
                ('tipo', models.CharField(choices=[('IMG', 'Imagen'), ('FILE', 'Archivo')], default='FILE', max_length=4)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('detalle_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='activos.detallemantenimiento')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=100)),
                ('nombre', models.CharField(max_length=120)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='activos.itemmantenible')),
            ],
            options={
                'ordering': ('nombre', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PlantillaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('PRE', 'Preventivo'), ('COR', 'Correctivo')], default='PRE', max_length=3)),
                ('es_global', models.BooleanField(default=False, help_text='Disponible para cualquier activo')),
                ('version', models.PositiveIntegerField(default=1)),
                ('vigente', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantillas', to='activos.activo')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('falla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas', to='activos.catalogofalla')),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantillas', to='activos.familiaactivo')),
            ],
            options={
                'ordering': ['-creado_en', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlanPreventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('trigger', models.CharField(choices=[('DIAS', 'Por tiempo'), ('CICL', 'Por ciclos'), ('EVT', 'Por evento')], default='DIAS', max_length=4)),
                ('cada_n_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('cada_n_ciclos', models.PositiveIntegerField(blank=True, null=True)),
                ('ultima_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('proxima_fecha', models.DateField(blank=True, null=True)),
                ('activo_en', models.BooleanField(default=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_preventivos', to='activos.activo')),
                ('plantilla', models.ForeignKey(limit_choices_to={'tipo': 'PRE'}, on_delete=django.db.models.deletion.PROTECT, to='activos.plantillachecklist')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCiclosSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.PositiveIntegerField()),
                ('semana', models.PositiveIntegerField()),
                ('ciclos', models.PositiveIntegerField(default=0)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_ciclos', to='activos.activo')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('SIN', 'Sin asignar OT'), ('PEN', 'Pendiente'), ('PRO', 'En Progreso'), ('REV', 'Pendiente Revisión'), ('CER', 'Cerrada')], default='PEN', max_length=3)),
                ('tipo', models.CharField(choices=[('PRE', 'Preventivo'), ('COR', 'Correctivo')], default='PRE', max_length=3)),
                ('titulo', models.CharField(default='', max_length=160)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('prioridad', models.CharField(choices=[('NONE', 'Ninguna'), ('BAJA', 'Baja'), ('MEDI', 'Media'), ('ALTA', 'Alta')], default='NONE', max_length=4)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('recurrencia', models.CharField(choices=[('NONE', 'No se repite'), ('DAIL', 'Diario'), ('WEEK', 'Semanal'), ('MDATE', 'Mensualmente por fecha'), ('MDOW', 'Mensualmente por día de la semana'), ('YEAR', 'Anual')], default='NONE', max_length=5)),
                ('tiempo_estimado_minutos', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('anio_ejecucion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('semana_ejecucion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lectura_ejecucion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='activos.activo')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('completado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_completadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
                ('falla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots', to='activos.catalogofalla')),
                ('plantilla_aplicada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_usadas', to='activos.plantillachecklist')),
            ],
            options={
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('INICIO', 'Inicio'), ('Taller Moldes', 'Taller Moldes'), ('Alistamiento Moldes', 'Alistamiento Moldes'), ('Montaje Moldes', 'Montaje Moldes'), ('Planta - Producción', 'Planta - Producción')], max_length=100)),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='novedades/%Y/%m/%d/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='activos.activo')),
                ('falla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades', to='activos.catalogofalla')),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_reportadas', to=settings.AUTH_USER_MODEL)),
                ('orden_mantenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades', to='activos.registromantenimiento')),
            ],
        ),
        migrations.AddField(
            model_name='detallemantenimiento',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='activos.registromantenimiento'),
        ),
        migrations.CreateModel(
            name='AdjuntoWO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=activos.models.ot_adjuntos_path)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wo_adjuntos', to=settings.AUTH_USER_MODEL)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='activos.registromantenimiento')),
            ],
            options={
                'verbose_name': 'Adjunto de OT',
                'verbose_name_plural': 'Adjuntos de OT',
            },
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=100)),
                ('nombre', models.CharField(max_length=120)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sistemas', to='activos.activo')),
            ],
            options={
                'ordering': ('nombre', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Subsistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=100)),
                ('nombre', models.CharField(max_length=120)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsistemas', to='activos.sistema')),
            ],
            options={
                'ordering': ('nombre', 'id'),
            },
        ),
        migrations.AddField(
            model_name='itemmantenible',
            name='subsistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='activos.subsistema'),
        ),
        migrations.CreateModel(
            name='PlantillaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatorio', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('notas_sugeridas', models.TextField(blank=True)),
                ('requiere_evidencia', models.BooleanField(default=False)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='activos.plantillachecklist')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.tareamantenimiento')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='detallemantenimiento',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.tareamantenimiento'),
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('INDUSTRIA', 'Industria'), ('EMPRESA', 'Empresa'), ('PLANTA', 'Planta'), ('PROCESO', 'Proceso'), ('SECCION', 'Sección / Sistema'), ('UNIDAD', 'Unidad de equipo'), ('SUBUNIDAD', 'Subunidad / Subsistema'), ('ITEM', 'Item mantenible'), ('PARTE', 'Parte'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='activos.ubicacion')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.AddField(
            model_name='registromantenimiento',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='activos.ubicacion'),
        ),
        migrations.AddField(
            model_name='activo',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='activos.ubicacion'),
        ),
        migrations.AddIndex(
            model_name='plantillachecklist',
            index=models.Index(fields=['tipo', 'vigente'], name='activos_pla_tipo_6b4374_idx'),
        ),
        migrations.AddIndex(
            model_name='plantillachecklist',
            index=models.Index(fields=['es_global'], name='activos_pla_es_glob_1ee3be_idx'),
        ),
        migrations.AddIndex(
            model_name='plantillachecklist',
            index=models.Index(fields=['activo'], name='activos_pla_activo__e817ff_idx'),
        ),
        migrations.AddIndex(
            model_name='plantillachecklist',
            index=models.Index(fields=['familia'], name='activos_pla_familia_8bee93_idx'),
        ),
        migrations.AddIndex(
            model_name='plantillachecklist',
            index=models.Index(fields=['falla'], name='activos_pla_falla_i_e3f5e4_idx'),
        ),
        migrations.AddIndex(
            model_name='registrociclossemanal',
            index=models.Index(fields=['activo'], name='activos_reg_activo__3246b0_idx'),
        ),
        migrations.AddIndex(
            model_name='registrociclossemanal',
            index=models.Index(fields=['año', 'semana'], name='activos_reg_año_05018c_idx'),
        ),
        migrations.AddIndex(
            model_name='registrociclossemanal',
            index=models.Index(fields=['-fecha_carga'], name='activos_reg_fecha_c_42b263_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='registrociclossemanal',
            unique_together={('activo', 'año', 'semana')},
        ),
        migrations.AlterUniqueTogether(
            name='plantillaitem',
            unique_together={('plantilla', 'tarea')},
        ),
        migrations.AddIndex(
            model_name='registromantenimiento',
            index=models.Index(fields=['estado'], name='activos_reg_estado_815be4_idx'),
        ),
        migrations.AddIndex(
            model_name='registromantenimiento',
            index=models.Index(fields=['tipo'], name='activos_reg_tipo_828060_idx'),
        ),
        migrations.AddIndex(
            model_name='registromantenimiento',
            index=models.Index(fields=['prioridad'], name='activos_reg_priorid_59f742_idx'),
        ),
        migrations.AddIndex(
            model_name='registromantenimiento',
            index=models.Index(fields=['-fecha_creacion'], name='activos_reg_fecha_c_38dfe1_idx'),
        ),
        migrations.AddIndex(
            model_name='registromantenimiento',
            index=models.Index(fields=['-fecha_inicio_ejecucion'], name='activos_reg_fecha_i_527582_idx'),
        ),
        migrations.AddIndex(
            model_name='registromantenimiento',
            index=models.Index(fields=['-fecha_cierre'], name='activos_reg_fecha_c_6bb63f_idx'),
        ),
        migrations.AddIndex(
            model_name='registromantenimiento',
            index=models.Index(fields=['vencimiento'], name='activos_reg_vencimi_4222fb_idx'),
        ),
        migrations.AddIndex(
            model_name='registromantenimiento',
            index=models.Index(fields=['activo'], name='activos_reg_activo__421eea_idx'),
        ),
        migrations.AddIndex(
            model_name='registromantenimiento',
            index=models.Index(fields=['asignado_a'], name='activos_reg_asignad_06b2c8_idx'),
        ),
        migrations.AddIndex(
            model_name='registromantenimiento',
            index=models.Index(fields=['ubicacion'], name='activos_reg_ubicaci_43cbcb_idx'),
        ),
    ]
