# Generated by Django 5.2.5 on 2025-08-14 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('numero_activo', models.CharField(max_length=255, verbose_name='# Activo')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso')),
            ],
        ),
        migrations.CreateModel(
            name='TareaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Tarea')),
                ('descripcion', models.TextField(blank=True, help_text='Instrucciones detalladas de la tarea.')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCiclosSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.PositiveIntegerField()),
                ('semana', models.PositiveIntegerField()),
                ('ciclos', models.PositiveIntegerField(default=0)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_ciclos', to='activos.activo')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('PRO', 'En Progreso'), ('REV', 'Pendiente Revisión'), ('COM', 'Completado')], default='PEN', max_length=3)),
                ('tipo', models.CharField(choices=[('PRE', 'Preventivo'), ('COR', 'Correctivo')], default='PRE', max_length=3)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='activos.activo')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('completado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_completadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.registromantenimiento')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.tareamantenimiento')),
            ],
        ),
    ]
