# Generated by Django 5.2.5 on 2025-08-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromantenimiento',
            name='anio_ejecucion',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registromantenimiento',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registromantenimiento',
            name='lectura_ejecucion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='registromantenimiento',
            name='semana_ejecucion',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registromantenimiento',
            name='estado',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('PRO', 'En Progreso'), ('REV', 'Pendiente Revisión'), ('CER', 'Cerrada')], default='PEN', max_length=3),
        ),
    ]
