# Generated by Django 5.2.5 on 2025-08-22 12:27

from django.db import migrations
from django.utils import timezone



def forward(apps, schema_editor):
    OT = apps.get_model('activos', 'RegistroMantenimiento')
    ahora = timezone.now()
    # Si existían OTs con estado 'COM' en datos viejos, pásalas a 'CER'
    for ot in OT.objects.filter(estado='COM').iterator():
        ot.estado = 'CER'
        # completa sellos si faltan
        if getattr(ot, 'fecha_fin_ejecucion', None) is None:
            ot.fecha_fin_ejecucion = ahora
        if getattr(ot, 'fecha_cierre', None) is None:
            ot.fecha_cierre = ahora
        ot.save(update_fields=['estado', 'fecha_fin_ejecucion', 'fecha_cierre'])

class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_registromantenimiento_anio_ejecucion_and_more'),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]