# Generated by Django 5.1.11 on 2025-08-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activos", "0002_categoriaactivo_estadoactivo_activo_ubicacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activo",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes"),
        ),
    ]

