# Generated by Django 5.2.5 on 2025-08-22 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0003_unificar_estados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registromantenimiento',
            options={'ordering': ['-fecha_creacion', '-id']},
        ),
        migrations.AlterField(
            model_name='detallemantenimiento',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='activos.registromantenimiento'),
        ),
        migrations.AlterUniqueTogether(
            name='registrociclossemanal',
            unique_together={('activo', 'año', 'semana')},
        ),
        migrations.AddIndex(
            model_name='registrociclossemanal',
            index=models.Index(fields=['activo'], name='activos_reg_activo__3246b0_idx'),
        ),
        migrations.AddIndex(
            model_name='registrociclossemanal',
            index=models.Index(fields=['año', 'semana'], name='activos_reg_año_05018c_idx'),
        ),
        migrations.AddIndex(
            model_name='registrociclossemanal',
            index=models.Index(fields=['-fecha_carga'], name='activos_reg_fecha_c_42b263_idx'),
        ),
        migrations.AddIndex(
            model_name='registromantenimiento',
            index=models.Index(fields=['estado'], name='activos_reg_estado_815be4_idx'),
        ),
        migrations.AddIndex(
            model_name='registromantenimiento',
            index=models.Index(fields=['tipo'], name='activos_reg_tipo_828060_idx'),
        ),
        migrations.AddIndex(
            model_name='registromantenimiento',
            index=models.Index(fields=['-fecha_creacion'], name='activos_reg_fecha_c_38dfe1_idx'),
        ),
        migrations.AddIndex(
            model_name='registromantenimiento',
            index=models.Index(fields=['-fecha_inicio_ejecucion'], name='activos_reg_fecha_i_527582_idx'),
        ),
        migrations.AddIndex(
            model_name='registromantenimiento',
            index=models.Index(fields=['-fecha_cierre'], name='activos_reg_fecha_c_6bb63f_idx'),
        ),
        migrations.AddIndex(
            model_name='registromantenimiento',
            index=models.Index(fields=['activo'], name='activos_reg_activo__421eea_idx'),
        ),
        migrations.AddIndex(
            model_name='registromantenimiento',
            index=models.Index(fields=['asignado_a'], name='activos_reg_asignad_06b2c8_idx'),
        ),
    ]
