# Generated by Django 5.2.5 on 2025-08-25 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_alter_registromantenimiento_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('PRE', 'Preventivo'), ('COR', 'Correctivo')], default='PRE', max_length=3)),
                ('es_global', models.BooleanField(default=False, help_text='Disponible para cualquier activo')),
                ('version', models.PositiveIntegerField(default=1)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantillas', to='activos.activo')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatorio', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('notas_sugeridas', models.TextField(blank=True)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='activos.plantillachecklist')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.tareamantenimiento')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='plantillachecklist',
            index=models.Index(fields=['tipo'], name='activos_pla_tipo_c89303_idx'),
        ),
        migrations.AddIndex(
            model_name='plantillachecklist',
            index=models.Index(fields=['es_global'], name='activos_pla_es_glob_1ee3be_idx'),
        ),
        migrations.AddIndex(
            model_name='plantillachecklist',
            index=models.Index(fields=['activo'], name='activos_pla_activo__e817ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plantillaitem',
            unique_together={('plantilla', 'tarea')},
        ),
    ]
