# Generated by Django 5.2.5 on 2025-09-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_novedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='novedades/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='etapa',
            field=models.CharField(choices=[('Taller Moldes', 'Taller Moldes'), ('Alistamiento Moldes', 'Alistamiento Moldes'), ('Montaje Moldes', 'Montaje Moldes'), ('Planta - Producción', 'Planta - Producción')], max_length=100),
        ),
    ]
