# Generated by Django 5.2.5 on 2025-09-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_novedad_archivo_alter_novedad_etapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='etapa',
            field=models.CharField(choices=[('INICIO', 'Inicio'), ('Taller Moldes', 'Taller Moldes'), ('Alistamiento Moldes', 'Alistamiento Moldes'), ('Montaje Moldes', 'Montaje Moldes'), ('Planta - Producción', 'Planta - Producción')], max_length=100),
        ),
        migrations.AlterField(
            model_name='registromantenimiento',
            name='estado',
            field=models.CharField(choices=[('SIN', 'Sin asignar OT'), ('PEN', 'Pendiente'), ('PRO', 'En Progreso'), ('REV', 'Pendiente Revisión'), ('CER', 'Cerrada')], default='PEN', max_length=3),
        ),
    ]
