# Generated by Django 5.2.5 on 2025-08-25 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_plantillachecklist_plantillaitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamiliaActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanPreventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('trigger', models.CharField(choices=[('DIAS', 'Por tiempo'), ('CICL', 'Por ciclos'), ('EVT', 'Por evento')], default='DIAS', max_length=4)),
                ('cada_n_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('cada_n_ciclos', models.PositiveIntegerField(blank=True, null=True)),
                ('ultima_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('proxima_fecha', models.DateField(blank=True, null=True)),
                ('activo_en', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='detallemantenimiento',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.RemoveIndex(
            model_name='plantillachecklist',
            name='activos_pla_tipo_c89303_idx',
        ),
        migrations.AddField(
            model_name='detallemantenimiento',
            name='obligatorio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detallemantenimiento',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detallemantenimiento',
            name='requiere_evidencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plantillachecklist',
            name='vigente',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plantillaitem',
            name='requiere_evidencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registromantenimiento',
            name='plantilla_aplicada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_usadas', to='activos.plantillachecklist'),
        ),
        migrations.AddField(
            model_name='plantillachecklist',
            name='falla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas', to='activos.catalogofalla'),
        ),
        migrations.AddField(
            model_name='registromantenimiento',
            name='falla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots', to='activos.catalogofalla'),
        ),
        migrations.AddField(
            model_name='activo',
            name='familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='activos.familiaactivo'),
        ),
        migrations.AddField(
            model_name='plantillachecklist',
            name='familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantillas', to='activos.familiaactivo'),
        ),
        migrations.AddIndex(
            model_name='plantillachecklist',
            index=models.Index(fields=['tipo', 'vigente'], name='activos_pla_tipo_6b4374_idx'),
        ),
        migrations.AddIndex(
            model_name='plantillachecklist',
            index=models.Index(fields=['familia'], name='activos_pla_familia_8bee93_idx'),
        ),
        migrations.AddIndex(
            model_name='plantillachecklist',
            index=models.Index(fields=['falla'], name='activos_pla_falla_i_e3f5e4_idx'),
        ),
        migrations.AddField(
            model_name='planpreventivo',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_preventivos', to='activos.activo'),
        ),
        migrations.AddField(
            model_name='planpreventivo',
            name='plantilla',
            field=models.ForeignKey(limit_choices_to={'tipo': 'PRE'}, on_delete=django.db.models.deletion.PROTECT, to='activos.plantillachecklist'),
        ),
    ]
