# Generated by Django 5.2.5 on 2025-09-08 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0006_alter_novedad_etapa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('archivo', models.FileField(upload_to='activos/docs/%Y/%m/%d/')),
                ('subido', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='activos.activo')),
            ],
        ),
    ]
