# Generated by Django 5.2.5 on 2025-08-26 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0006_catalogofalla_familiaactivo_planpreventivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromantenimiento',
            name='estado',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('PRO', 'En Progreso'), ('REV', 'Pendiente Revisión'), ('COM', 'Completada')], default='PEN', max_length=3),
        ),
        migrations.CreateModel(
            name='EvidenciaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='evidencias_mantenimiento/%Y/%m/%d/')),
                ('tipo', models.CharField(choices=[('IMG', 'Imagen'), ('FILE', 'Archivo')], default='FILE', max_length=4)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('detalle_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='activos.detallemantenimiento')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
        ),
    ]
