# Generated by Django 5.2.5 on 2025-09-09 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0007_documentoactivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMantenible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='activo',
            name='tag',
            field=models.CharField(blank=True, max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='activo',
            name='item_mantenible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='activos.itemmantenible'),
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='activos.itemmantenible')),
            ],
        ),
        migrations.AddField(
            model_name='activo',
            name='parte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='activos.parte'),
        ),
        migrations.AddField(
            model_name='activo',
            name='planta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='activos.planta'),
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sistemas', to='activos.planta')),
            ],
        ),
        migrations.AddField(
            model_name='activo',
            name='sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='activos.sistema'),
        ),
        migrations.CreateModel(
            name='SubSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsistemas', to='activos.sistema')),
            ],
        ),
        migrations.AddField(
            model_name='itemmantenible',
            name='subsistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='activos.subsistema'),
        ),
        migrations.AddField(
            model_name='activo',
            name='subsistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='activos.subsistema'),
        ),
    ]
