# Generated by Django 5.2.5 on 2025-09-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0008_itemmantenible_planta_activo_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='tag',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
