# Generated by Django 5.2.5 on 2025-09-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0009_alter_activo_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='item_mantenible',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='parte',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='planta',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='sistema',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='subsistema',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='tag',
        ),
        migrations.AddField(
            model_name='activo',
            name='componentes',
            field=models.ManyToManyField(blank=True, related_name='es_parte_de', to='activos.activo', verbose_name='Componentes'),
        ),
    ]
