# Generated by Django 5.2.5 on 2025-09-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0010_remove_activo_item_mantenible_remove_activo_parte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parte',
            name='item',
        ),
        migrations.RemoveField(
            model_name='sistema',
            name='planta',
        ),
        migrations.RemoveField(
            model_name='subsistema',
            name='sistema',
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='tipo',
            field=models.CharField(choices=[('INDUSTRIA', 'Industria'), ('EMPRESA', 'Empresa'), ('PLANTA', 'Planta'), ('PROCESO', 'Proceso'), ('SECCION', 'Sección / Sistema'), ('UNIDAD', 'Unidad de equipo'), ('SUBUNIDAD', 'Subunidad / Subsistema'), ('ITEM', 'Item mantenible'), ('PARTE', 'Parte'), ('OTRO', 'Otro')], default='OTRO', max_length=20),
        ),
        migrations.DeleteModel(
            name='ItemMantenible',
        ),
        migrations.DeleteModel(
            name='Parte',
        ),
        migrations.DeleteModel(
            name='Planta',
        ),
        migrations.DeleteModel(
            name='Sistema',
        ),
        migrations.DeleteModel(
            name='SubSistema',
        ),
    ]
