# Generated by Django 5.2.5 on 2025-09-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0011_remove_parte_item_remove_sistema_planta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='componentes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'ubicacion__tipo__in': ['SUBUNIDAD', 'ITEM', 'PARTE']}, related_name='es_parte_de', to='activos.activo', verbose_name='Componentes'),
        ),
    ]
