# Generated by Django 5.2.5 on 2025-09-09 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0012_alter_activo_componentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMantenible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100)),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100)),
                ('nombre', models.CharField(max_length=120)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='activos.itemmantenible')),
            ],
        ),
        migrations.CreateModel(
            name='Subsistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100)),
                ('nombre', models.CharField(max_length=120)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsistemas', to='activos.activo')),
            ],
        ),
        migrations.AddField(
            model_name='itemmantenible',
            name='subsistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='activos.subsistema'),
        ),
    ]
